# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ed002bf157d68fd5f683ae36af0ed3af999440eb24a01fd7b8fa1829716998711381e2887f46452a2b0a5381673faa5d13193e469a51596af85e940aa5cec4b

test:
  secret_key_base: 244d65699b8d2e29a5c8eef66681a7b6a4ca3e923dca3cdec3a913dc409807474d1ba3f7db9a8b620693f0f07cdb934c57256ac06cff7bdac564afb2b68a1f27

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
